In [423]:
import csv
import numpy as np
import pandas as pd


In [424]:
with open('tabla_reports.csv', newline='') as File:  
    reader = csv.reader(File)
    for row in reader:
        print(row)

['company_name', 'id', 'reason_table', 'claim_reference', 'claim_type', 'claim_open_date', 'disbursement_status', 'disbursement_created_date', 'amount']
['Reynards Legal Limited', '2', 'created', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', '0']
['Reynards Legal Limited', '3', 'paid', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', '0']
['Reynards Legal Limited', '4', 'created', 'CW101008', 'CWI', '03/10/2018', 'NULL', 'NULL', '0']
['Reynards Legal Limited', '5', 'created', 'CW101008', 'CWI', '03/10/2018', 'Cancelled', '03/10/2018', '0']
['Reynards Legal Limited', '6', 'created', 'CW101008', 'CWI', '03/10/2018', 'Cancelled', '03/10/2018', '2184']
['Reynards Legal Limited', '7', 'calculated', 'CW101008', 'CWI', '03/10/2018', 'NULL', 'NULL', '0']
['Reynards Legal Limited', '8', 'cancelled', 'CW101008', 'CWI', '03/10/2018', 'Cancelled', '03/10/2018', '0']
['Reynards Legal Limited', '9', 'cancelled', 'CW101008', 'CWI', '03/10/2018', 'Cancelled', '03/10/2018', '2184']
['Just Costs Solicitors Limited', '

In [425]:
df = pd.read_csv('tabla_reports.csv', sep=',')
datos = df.values

In [426]:
df.head(10)

company_name  id reason_table claim_reference claim_type  \
0         Reynards Legal Limited   2      created             NaN        NaN   
1         Reynards Legal Limited   3         paid             NaN        NaN   
2         Reynards Legal Limited   4      created        CW101008        CWI   
3         Reynards Legal Limited   5      created        CW101008        CWI   
4         Reynards Legal Limited   6      created        CW101008        CWI   
5         Reynards Legal Limited   7   calculated        CW101008        CWI   
6         Reynards Legal Limited   8    cancelled        CW101008        CWI   
7         Reynards Legal Limited   9    cancelled        CW101008        CWI   
8  Just Costs Solicitors Limited  10      created             NaN        NaN   
9         Reynards Legal Limited  11   calculated        CW101008        CWI   

  claim_open_date disbursement_status disbursement_created_date  amount  
0             NaN                 NaN                       NaN     0.0  
1             NaN                 NaN                       NaN     0.0  
2      03/10/2018                 NaN                       NaN     0.0  
3      03/10/2018           Cancelled                03/10/2018     0.0  
4      03/10/2018           Cancelled                03/10/2018  2184.0  
5      03/10/2018                 NaN                       NaN     0.0  
6      03/10/2018           Cancelled                03/10/2018     0.0  
7      03/10/2018           Cancelled                03/10/2018  2184.0  
8             NaN                 NaN                       NaN     0.0  
9      03/10/2018                 NaN                       NaN     0.0

In [427]:
#datos


In [428]:
type(datos)

numpy.ndarray

In [429]:
# csv = np.genfromtxt ('tabla_reports.csv', delimiter=",",dtype = None) # con no tipos

In [430]:
csv = np.genfromtxt ('tabla_reports.csv', delimiter=",",skip_header=0)

In [431]:
# get all data as panda DataFrame
data = pd.read_csv("tabla_reports.csv")
print(data)

# get values as numpy array
data_ar = data.values
header = []# numpy.ndarray, every element is a row
for row in data_ar:
    # print(row)
    sum = 0
    count = 0
    for reason_table in np.nditer(row, flags=["refs_OK"], op_flags=["readwrite"]):
        header

                     company_name   id reason_table claim_reference  \
0          Reynards Legal Limited    2      created             NaN   
1          Reynards Legal Limited    3         paid             NaN   
2          Reynards Legal Limited    4      created        CW101008   
3          Reynards Legal Limited    5      created        CW101008   
4          Reynards Legal Limited    6      created        CW101008   
5          Reynards Legal Limited    7   calculated        CW101008   
6          Reynards Legal Limited    8    cancelled        CW101008   
7          Reynards Legal Limited    9    cancelled        CW101008   
8   Just Costs Solicitors Limited   10      created             NaN   
9          Reynards Legal Limited   11   calculated        CW101008   
10       Milestone Claims Limited   12      created             NaN   
11  Just Costs Solicitors Limited   13      created      179600.cwi   
12  Just Costs Solicitors Limited   14      created      179600.cwi   
13  Ju

ValueError: Unexpected iterator global flag "refs_OK"

In [433]:
type(data_ar)

numpy.ndarray

In [434]:
print(data_ar.flags)

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [435]:
array = data_ar[:10]

In [437]:
#array

** INDICES CORRESPONDIENTES A LOS LOS MAYORES VALORES

* forma1

In [438]:
import heapq
a = np.array([25,2,9,5,1,7,40])
heapq.nlargest(3, range(len(a)), a.take)


[6, 0, 2]

* forma2

In [439]:
ind = np.argpartition(a, -4)[-4:]
ind

array([5, 2, 0, 6], dtype=int64)

* forma3

In [440]:
idx = (-a).argsort()[:]
idx

array([6, 0, 2, 5, 3, 1, 4], dtype=int64)

* forma4 : funcion para obtener los indices de aquellos elementos mayores

In [441]:
def largest_indices(arry, n):
    """Returns the n largest indices from a numpy array."""
    flat = arry.flatten()
    indices = np.argpartition(flat, -n)[-n:]
    indices = indices[np.argsort(-flat[indices])]
    return np.unravel_index(indices, arry.shape)

In [442]:
largest_indices(a, n=len(a)) # obtengo los indices

(array([6, 0, 2, 5, 3, 1, 4], dtype=int64),)

In [443]:
a[largest_indices(a,n=len(a))] # obtengo los valores ordenados

array([40, 25,  9,  7,  5,  2,  1])

* forma 5

In [444]:
K = 4 # We want the indices of the four largest values
a = np.array([0, 8, 0, 4, 5, 8, 8, 0, 4, 2])
resultado = np.argpartition(a,-K)[-K:]
resultado

array([4, 1, 5, 6], dtype=int64)

* forma6 = cuando tenemos una multidimensional

In [445]:
arr = np.array([[2,45,7],[39,45,2]])
N = len(arr)
indices = np.argpartition(arr, 1, axis=1)[:, :]
indices

array([[0, 2, 1],
       [2, 0, 1]], dtype=int64)

In [446]:
print(type(array))

<class 'numpy.ndarray'>


In [447]:
indices = np.argsort(arr, axis=1)[-N:, :]
indices

array([[0, 2, 1],
       [2, 0, 1]], dtype=int64)

* forma7

In [448]:
A = [2,45,7,39,50,2]
from operator import itemgetter
from heapq import nlargest
result = nlargest(len(A), enumerate(A), itemgetter(1))
result

[(4, 50), (1, 45), (3, 39), (2, 7), (0, 2), (5, 2)]

* forma8 >> con funcion

In [449]:
def max_indices(arr, k):
    '''
    Returns the indices of the k first largest elements of arr
    (in descending order in values)
    '''
    assert k <= arr.size, 'k should be smaller or equal to the array size'
    arr_ = arr.astype(float)  # make a copy of arr
    max_idxs = []
    for _ in range(k):
        max_element = np.max(arr_)
        if np.isinf(max_element):
            break
        else:
            idx = np.where(arr_ == max_element)
        max_idxs.append(idx)
        arr_[idx] = -np.inf
    return max_idxs

In [450]:
arr = np.array([[2,45,7],[39,45,2],[2,1,7],[2,450,266]])

In [451]:
k=(len(arr))
k

4

In [452]:
def max_indices(arr, k):
    '''
    Returns the indices of the k first largest elements of arr
    (in descending order in values)
    '''
    assert k <= arr.size, 'k should be smaller or equal to the array size'
    arr_ = arr.astype(float)  # make a copy of arr
    max_idxs = []
    for _ in range(k):
        max_element = np.max(arr_)
        if np.isinf(max_element):
            break
        else:
            idx = np.where(arr_ == max_element)
        max_idxs.append(idx)
        arr_[idx] = -np.inf
    return max_idxs

In [453]:
max_indices(arr, k)

[(array([3], dtype=int64), array([1], dtype=int64)),
 (array([3], dtype=int64), array([2], dtype=int64)),
 (array([0, 1], dtype=int64), array([1, 1], dtype=int64)),
 (array([1], dtype=int64), array([0], dtype=int64))]

In [454]:
arr[max_indices(arr, 4)[0]][0] # retorna el mayor valor total 

450

In [455]:
arr

array([[  2,  45,   7],
       [ 39,  45,   2],
       [  2,   1,   7],
       [  2, 450, 266]])

In [456]:
arr[max_indices(arr, 4)[3]][0]  # no lo entiendo

39

In [457]:
array = np.array([[1,45,7],[39,45,2],[2,3,7],[2,450,266]])

* insertar valores en una matriz

* forma 1

In [458]:
b = np.insert(array, 1, values=0, axis=1) # 1 indeca la posicion donde queremos
b

array([[  1,   0,  45,   7],
       [ 39,   0,  45,   2],
       [  2,   0,   3,   7],
       [  2,   0, 450, 266]])

* forma2

In [307]:
source = array.tolist()
result = [row + ['total'] for row in source]
b = np.array(result)
b

array([['1', '45', '7', 'total'],
       ['39', '45', '2', 'total'],
       ['2', '3', '7', 'total'],
       ['2', '450', '266', 'total']], dtype='<U11')

In [310]:
array


array([[  1,  45,   7],
       [ 39,  45,   2],
       [  2,   3,   7],
       [  2, 450, 266]])

In [317]:
# new_col = np.array(['accepted', 'declain', 'accepted','paid'])
new_col = np.array([0,0,0,0])
idx =3
np.insert(array, idx, new_col, axis=1)

array([[  1,  45,   7,   0],
       [ 39,  45,   2,   0],
       [  2,   3,   7,   0],
       [  2, 450, 266,   0]])

* como modificar un valor

In [322]:
A = np.matrix(data_ar[:5])

In [328]:
A[:,[2]]

matrix([['no'],
        ['paid'],
        ['created'],
        ['created'],
        ['created']], dtype=object)

In [ ]:
np.asarray(A)[:,[3]]='REBECA'

In [ ]:
b =['paid']

* valores unicos

In [355]:
array = np.array([[  1,  1,   'a'],[ 1,  1,   2],[  2,   3,   7],[  2, 2, 3]])
array

array([['1', '1', 'a'],
       ['1', '1', '2'],
       ['2', '3', '7'],
       ['2', '2', '3']], dtype='<U11')

In [357]:
new_array = [tuple(row) for row in array[:,[2]]]
uniques = np.unique(new_array)
uniques

array(['2', '3', '7', 'a'], dtype='<U1')

In [347]:
b

array([[  1,  45,   7],
       [  2, 450, 266],
       [ 39,  45,   2],
       [  2,   3,   7]])

* cambiar valores de una columna

In [358]:
np.asarray(A)[:,[3]]='no'
A

matrix([['no', 'no', 'no', 'no', 'no', 'no', 'no', 'no', 'no'],
        ['no', 3, 'paid', 'no', nan, nan, nan, nan, 0.0],
        ['no', 4, 'created', 'no', 'CWI', '03/10/2018', nan, nan, 0.0],
        ['no', 5, 'created', 'no', 'CWI', '03/10/2018', 'Cancelled',
         '03/10/2018', 0.0],
        ['no', 6, 'created', 'no', 'CWI', '03/10/2018', 'Cancelled',
         '03/10/2018', 2184.0]], dtype=object)

* guardo los datos

In [473]:
import csv
import numpy as np
import pandas as pd


In [474]:
with open('tabla_reports.csv', newline='') as File:  
    reader = csv.reader(File)
    header = []
    for row in reader:
        header.append(row)

In [475]:
array = np.array(header)
array.shape

(101, 9)

In [476]:
matrix

matrix([[  1,  45,   7],
        [ 39,  45,   2],
        [  2,   3,   7],
        [  2, 450, 266]])

In [477]:

matrix = np.matrix(array)
my_array = array[:7,:9]
arr = array[:7,[0,1,2,5,8]]
arr

array([['company_name', 'id', 'reason_table', 'claim_open_date',
        'amount'],
       ['Reynards Legal Limited', '2', 'created', 'NULL', '0'],
       ['Reynards Legal Limited', '3', 'paid', 'NULL', '0'],
       ['Reynards Legal Limited', '4', 'created', '03/10/2018', '0'],
       ['Reynards Legal Limited', '5', 'created', '03/10/2018', '0'],
       ['Reynards Legal Limited', '6', 'created', '03/10/2018', '2184'],
       ['Reynards Legal Limited', '7', 'calculated', '03/10/2018', '0']],
      dtype='<U29')

In [485]:
a = np.array(arr[:,[-1]])

* removing nan values from an array

In [491]:
def jsonify(array):
    json_data = dict()
    for key, value in data.iteritems():
        if isinstance(value, list): # for lists
            value = [ jsonify(item) if isinstance(item, dict) else item for item in value ]
        if isinstance(value, dict): # for nested lists
            value = jsonify(value)
        if isinstance(key, int): # if key is integer: > to string
            key = str(key)
        if type(value).__module__=='numpy': # if value is numpy.*: > to python list
            value = value.tolist()
        json_data[key] = value
    return json_data

In [515]:
# jsonify(array)

* lambda, map

In [536]:
x = np.array([[1,3,6,88,9]])
y = []

In [537]:
for v in x:
    y = [v*5]
y

[array([  5,  15,  30, 440,  45])]

In [539]:
y = [v*5 for v in x]
y

[array([  5,  15,  30, 440,  45])]

In [543]:
y = list(map(lambda v : v -2, x))
y

[array([-1,  1,  4, 86,  7])]

In [553]:
arr.shape


(7, 5)

In [557]:
x = arr[:,[1,2,4]]
y = []

In [559]:
x

array([['id', 'reason_table', 'amount'],
       ['2', 'created', '0'],
       ['3', 'paid', '0'],
       ['4', 'created', '0'],
       ['5', 'created', '0'],
       ['6', 'created', '2184'],
       ['7', 'calculated', '0']], dtype='<U29')

In [576]:
x[:,[2]].tolist()

[['amount'], ['0'], ['0'], ['0'], ['0'], ['2184'], ['0']]

In [586]:
y = map(lambda v : v * 5, filter(lambda u : u % 2, x))
y

In [591]:
x = [2, 3, 4]
y = [4, 5]
z = [v + w for v in x for w in y]
z

[6, 7, 7, 8, 8, 9]

In [595]:
x = [2, 3, 4]
y = [4, 5]
t = map(lambda v : map(lambda w : v + w, y), x)
t == [[6, 7], [7, 8], [8, 9]]


False

In [598]:
[v + w for v in x for w in y]

[6, 7, 7, 8, 8, 9]