In [367]:
import csv
import numpy as np
import pandas as pd


In [368]:

with open('tabla_reports.csv', newline='') as File:  
    reader = csv.reader(File)
    for row in reader:
        print(row)

['company_name', 'id', 'reason_table', 'claim_reference', 'claim_type', 'claim_open_date', 'disbursement_status', 'disbursement_created_date', 'amount']
['Reynards Legal Limited', '2', 'created', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', '0']
['Reynards Legal Limited', '3', 'paid', 'NULL', 'NULL', 'NULL', 'NULL', 'NULL', '0']
['Reynards Legal Limited', '4', 'created', 'CW101008', 'CWI', '03/10/2018', 'NULL', 'NULL', '0']
['Reynards Legal Limited', '5', 'created', 'CW101008', 'CWI', '03/10/2018', 'Cancelled', '03/10/2018', '0']
['Reynards Legal Limited', '6', 'created', 'CW101008', 'CWI', '03/10/2018', 'Cancelled', '03/10/2018', '2184']
['Reynards Legal Limited', '7', 'calculated', 'CW101008', 'CWI', '03/10/2018', 'NULL', 'NULL', '0']
['Reynards Legal Limited', '8', 'cancelled', 'CW101008', 'CWI', '03/10/2018', 'Cancelled', '03/10/2018', '0']
['Reynards Legal Limited', '9', 'cancelled', 'CW101008', 'CWI', '03/10/2018', 'Cancelled', '03/10/2018', '2184']
['Just Costs Solicitors Limited', '

In [369]:
df = pd.read_csv('tabla_reports.csv', sep=',')
datos = df.values

In [371]:
df.head(1)

company_name  id reason_table claim_reference claim_type  \
0  Reynards Legal Limited   2      created             NaN        NaN   

  claim_open_date disbursement_status disbursement_created_date  amount  
0             NaN                 NaN                       NaN     0.0

In [372]:
#datos

In [373]:
type(datos)

numpy.ndarray

In [374]:
# csv = np.genfromtxt ('tabla_reports.csv', delimiter=",",dtype = None) # con no tipos

In [375]:
csv = np.genfromtxt ('tabla_reports.csv', delimiter=",",skip_header=0)

In [376]:
# get all data as panda DataFrame
data = pd.read_csv("tabla_reports.csv")
#print(data)

# get values as numpy array
data_ar = data.values
header = []# numpy.ndarray, every element is a row
for row in data_ar:
    # print(row)
    sum = 0
    count = 0
    for reason_table in np.nditer(row, flags=["refs_OK"], op_flags=["readwrite"]):
        #print(header) 

SyntaxError: unexpected EOF while parsing (<ipython-input-376-d16ba1b455b1>, line 13)

In [377]:
type(data_ar)

numpy.ndarray

In [378]:
print(data_ar.flags)

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [379]:
csv.shape

(101, 9)

In [380]:
csv.dtype

dtype('float64')

In [11]:
#csv[0:]

In [12]:
datos.ndim

2

In [13]:
datos.itemsize

8

In [14]:
len(datos)

100

In [15]:
type(datos)

numpy.ndarray

In [16]:
matriz = np.asmatrix(datos)

In [17]:
np = np.array(datos)

In [18]:
print(type(matriz))
print(type(csv))
print(type(datos))
print(type(np))

<class 'numpy.matrixlib.defmatrix.matrix'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [19]:
matriz.shape

(100, 9)

* algunas cositas

In [381]:
x_data = matriz[: , : -1]
# x_data

In [24]:
y_data = matriz[: , -1] # imprimo ultima columna de cada row
#y_data

In [25]:
company_name = matriz[: , 0:4]

In [26]:
company_name.shape

(100, 4)

 * valores unicos de la columna

In [382]:
import numpy as np
# todas las row de las columnas 0, 2, -1
compania = matriz[:,[0,2,-1]]
# compania
comp_array = np.array(compania)
col_unique = (sorted(set(comp_array[:,1]))) # valores unicos de la columna
col_unique

['calculated', 'cancelled', 'created', 'paid']

In [384]:
comp_array[:2]

array([['Reynards Legal Limited', 'created', 0.0],
       ['Reynards Legal Limited', 'paid', 0.0]], dtype=object)

* filtrando columnas

In [386]:
A = [ [ind,row[0],row[-1]] for ind,row in enumerate(comp_array) if row[-1] > 0]

In [388]:
# A

In [390]:
a = [row for row in comp_array if row[1] != 'calculated' in comp_array]
# a

In [39]:
col_unique

['calculated', 'cancelled', 'created', 'paid']

* maskaras

In [393]:
mask = comp_array[:7,[1]]== "cancelled" 

mask

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True]])

In [394]:
b = np.where(mask,np.arange(mask.size),0)
# b
# np.maximum.accumulate(np.where(mask,np.arange(mask.size),0))

In [401]:
idx = np.maximum.accumulate(np.where(mask,np.arange(mask.size),0))
idx

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0],
       [0, 1, 2, 3, 4, 5, 6]], dtype=int32)

In [404]:
mask = comp_array[:10,[0,1,2]]== "cancelled" 
mask

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [405]:
np.count_nonzero(mask) # cuenta el numero de True

2

In [407]:
array  = np.array(comp_array[:5,[0,1,2]])
array

array([['Reynards Legal Limited', 'created', 0.0],
       ['Reynards Legal Limited', 'paid', 0.0],
       ['Reynards Legal Limited', 'created', 0.0],
       ['Reynards Legal Limited', 'created', 0.0],
       ['Reynards Legal Limited', 'created', 2184.0]], dtype=object)

In [409]:
array.shape

(5, 3)

In [408]:
y = array.shape[0]
x = array.shape[1]
print(y,x)


5 3


https://stackoverflow.com/questions/45768262/numpy-equivalent-of-if-else-without-loop?rq=1

In [412]:
for x in range(array.shape[0]): 
    for y in range(array.shape[1]):
        # print(x,y)

SyntaxError: unexpected EOF while parsing (<ipython-input-412-8ca571e5b442>, line 3)

* pivot-table adaptado

In [417]:
def pivot_table(array, col, row, val, action=len, row_list=None, add_col_total=True):
    '''le damos la matriz pero en forma array, especificamos la columna, la columna, la row, el valor y la acccion
        si le damos la row_list, seran los valores que busque para contarlos o sumar'''
  
    col_unique = list(sorted(set(array[:,col])))
    row_unique = row_list if row_list is not None else list(set(array[:,row]))
    row_unique = list(filter(None, row_unique))
    result_table = [[''] + row_unique]
    for c in col_unique:
        single_row = [c]
        for r in row_unique:
            value = action(array[(comp_array [:,col] == c) & (array[:,row] == r)][:,val])
            single_row.append(value)           
        if add_col_total:
            single_row.append(sum(single_row[1:]))
        result_table.append(single_row)
    if add_col_total:
        result_table[0] = result_table[0] + ['Total']
    return np.array(result_table, dtype=object)

In [418]:
# quiero saber la cantidad de razones por compania, la cantidad y el total

In [420]:
# pivot_table(comp_array, 1, 0, 2, action=len, row_list=['calculated', 'cancelled', 'created', 'paid'])

In [56]:
print(type(matriz))
print(type(csv))
print(type(datos))
print(type(np))
print(type(compania))

<class 'numpy.matrixlib.defmatrix.matrix'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'module'>
<class 'numpy.matrixlib.defmatrix.matrix'>


In [421]:
# todas las row de las columnas 0, 2, -1
array = np.array(matriz[:20,[0,2,3,5,1]])

* forma de crear una matriz

In [423]:
matrix = np.matrix('2 2 1; 7 7 1; 11 12 1')
array = np.array(matrix)

In [426]:
array

array([[ 2,  2,  1],
       [ 7,  7,  1],
       [11, 12,  1]])

* funcion que se supone que cuenta valores, pero no lo tengo claro

In [435]:
def counts_of_all_values_rowwise(array):
    # Valores exclusivos e suas contagens de linha inteligente
    num_counts_array = [np.unique(row, return_counts=True) for row in array]
    # Contagens de todos os valores linha inteligente
    contador = ([[int(b[a==i]) if i in a else 0 for i in np.unique(array)] for a, b in num_counts_array])
    return contador


In [434]:
array

array([[ 2,  2,  1],
       [ 7,  7,  1],
       [11, 12,  1]])

In [432]:
counts_of_all_values_rowwise(array)

[[1, 2, 0, 0, 0], [1, 0, 2, 0, 0], [1, 0, 0, 1, 1]]

* no se que hace

In [436]:
import numpy as np
a = np.array([1, 3, 7, 1])

doublediff = np.diff(np.sign(np.diff(a)))
picos = np.where(doublediff == -2)[0] + 1
print(picos)

[2]


* notas

In [437]:
comp_array = np.array(compania)
#comp_array

In [438]:
# todas las row de las columnas 0, 2, -1
compania = matriz[:,[0,2,-1]]

In [439]:
arr = np.array(compania[:10], dtype= object)

In [440]:
arr

array([['Reynards Legal Limited', 'created', 0.0],
       ['Reynards Legal Limited', 'paid', 0.0],
       ['Reynards Legal Limited', 'created', 0.0],
       ['Reynards Legal Limited', 'created', 0.0],
       ['Reynards Legal Limited', 'created', 2184.0],
       ['Reynards Legal Limited', 'calculated', 0.0],
       ['Reynards Legal Limited', 'cancelled', 0.0],
       ['Reynards Legal Limited', 'cancelled', 2184.0],
       ['Just Costs Solicitors Limited', 'created', 0.0],
       ['Reynards Legal Limited', 'calculated', 0.0]], dtype=object)

In [441]:
arr = np.random.randint(1,4, size=6)

In [442]:
arr = np.array(compania)
#arr

https://github.com/datasciencebrazil/exercicios-numpy/blob/master/exercicios_numpy.ipynb

In [443]:
matrix = np.matrix('2 2 1; 7 7 1; 11 12 1')
array = np.array(matrix)

In [444]:
array

array([[ 2,  2,  1],
       [ 7,  7,  1],
       [11, 12,  1]])

* construyendo una matriz pyhton a traves de la iteracion  

*No se que hace

In [455]:
pos_vec = np.array([7,0,0])

In [458]:
def delta_matrix(pos_vec):
    build=[]
    for i in pos_vec:
        build.append(i+pos_vec)
    return np.array(build)

In [459]:
delta_matrix(pos_vec)

array([[14,  7,  7],
       [ 7,  0,  0],
       [ 7,  0,  0]])

* otro ejercicio de generacion matrices

In [465]:
pos_vec2 = ['a','b','c']

In [466]:
pos_vec = ['b','b','b']

In [467]:
def delta_matrix2(pos_vec2):
    return np.array([pos_vec for i in pos_vec2 ])

In [468]:
delta_matrix2(pos_vec2)

array([['b', 'b', 'b'],
       ['b', 'b', 'b'],
       ['b', 'b', 'b']], dtype='<U1')

*  esta funcion suma el elemento derecho y el izquierdo de cada row, 
* luego recorre la matriz y suma ese elemento a cada uno de los items

In [484]:
matrix = np.matrix('2 2 1; 7 7 1; 11 12 1')
arr_red = np.array(matrix)

In [485]:
height

3

In [486]:
# esta funcion suma el elemento derecho y el izquierdo de cada row, 
# luego recorre la matriz y suma ese elemento a cada uno de los items

In [487]:
def media(arr_red):
    subtracted = np.ones_like(arr_red)
    height, width = arr_red.shape
    for row_no, row in enumerate(arr_red):   # keep the row number using enumerate
        left, right = row[0], row[-1]      # you need the first and last value of the ROW!
        average = (left + right) / 2.0
        total = (left + right)
        # Also use enumerate in the inner loop
        for col_no, element in enumerate(row):
            subtracted[row_no, col_no] = element + total
    return(subtracted)

In [488]:
media(arr_red)

array([[ 5,  5,  4],
       [15, 15,  9],
       [23, 24, 13]])

* calculo frecuencia

* forma1

In [490]:
import numpy as np
x = np.array([1,1,1,2,2,2,5,25,1,1])
y = np.bincount(x)
ii = np.nonzero(y)[0]
frecuencia = list(zip(ii, y[ii]))

In [491]:
frecuencia # del elemento 1 tenemos 5, del 2 tenemos 3

[(1, 5), (2, 3), (5, 1), (25, 1)]

In [494]:
np.vstack(frecuencia).T # otra forma de verlo

array([[ 1,  2,  5, 25],
       [ 5,  3,  1,  1]], dtype=int64)

* forma2

In [495]:
x = np.array(arr[:,[1]])
unique, counts = np.unique(x, return_counts = True)
print(np.asarray((unique, counts)).T)

[['calculated' 2]
 ['cancelled' 9]
 ['created' 88]
 ['paid' 1]]


In [293]:
x = np.array(arr[:,[1,0]])
unique, counts = np.unique(x, return_counts = True)
print(np.asarray((unique, counts)).T)

[['Just Costs Solicitors Limited' 90]
 ['Milestone Claims Limited' 1]
 ['Reynards Legal Limited' 9]
 ['calculated' 2]
 ['cancelled' 9]
 ['created' 88]
 ['paid' 1]]


* otra forma de contr valores

In [319]:
def unique(a):
    unique, counts = np.unique(a, return_counts=True)
    return np.asarray((unique, counts)).T

def unique_count(a):
    
    unique, inverse = np.unique(a, return_inverse=True)
    count = np.zeros(len(unique), np.int)
    np.add.at(count, inverse, 1)
    result.append(np.vstack((unique, count)).T)
    return result

In [496]:
unique_count(a)

[array([['Just Costs Solicitors Limited', '90'],
        ['Milestone Claims Limited', '1'],
        ['Reynards Legal Limited', '9'],
        ['calculated', '2'],
        ['cancelled', '9'],
        ['created', '88'],
        ['paid', '1']], dtype='<U29'),
 array([['Just Costs Solicitors Limited', '90'],
        ['Milestone Claims Limited', '1'],
        ['Reynards Legal Limited', '9'],
        ['calculated', '2'],
        ['cancelled', '9'],
        ['created', '88'],
        ['paid', '1']], dtype='<U29'),
 array([['Just Costs Solicitors Limited', '90'],
        ['Milestone Claims Limited', '1'],
        ['Reynards Legal Limited', '9'],
        ['calculated', '2'],
        ['cancelled', '9'],
        ['created', '88'],
        ['paid', '1']], dtype='<U29'),
 array([[1, 2],
        [3, 1],
        [7, 1]])]

In [499]:
a = x.tolist()
#a

In [323]:
unique_count(a)

[array([['Just Costs Solicitors Limited', '90'],
        ['Milestone Claims Limited', '1'],
        ['Reynards Legal Limited', '9'],
        ['calculated', '2'],
        ['cancelled', '9'],
        ['created', '88'],
        ['paid', '1']], dtype='<U29'),
 array([['Just Costs Solicitors Limited', '90'],
        ['Milestone Claims Limited', '1'],
        ['Reynards Legal Limited', '9'],
        ['calculated', '2'],
        ['cancelled', '9'],
        ['created', '88'],
        ['paid', '1']], dtype='<U29'),
 array([['Just Costs Solicitors Limited', '90'],
        ['Milestone Claims Limited', '1'],
        ['Reynards Legal Limited', '9'],
        ['calculated', '2'],
        ['cancelled', '9'],
        ['created', '88'],
        ['paid', '1']], dtype='<U29')]

In [502]:
# arr[:9]

In [503]:
# keys

* forma de sumar dos columas

In [517]:
a = np.matrix('1 2 3 4 5; 6 7 8 9 10; 11 12 13 14 15')
a

matrix([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]])

In [518]:
xs = a[:,:1]
ys = a[:,3:4]
xs

matrix([[ 1],
        [ 6],
        [11]])

In [519]:
ys

matrix([[ 4],
        [ 9],
        [14]])

In [520]:
import math
def distance(xs, ys):
    n = len(xs)
    
    for i in range(n):
        a = xs+ys
    return a

In [521]:
distance(xs, ys)

matrix([[ 5],
        [15],
        [25]])

In [ ]:
print(np.amax(a, axis=1)) #axis =0
print(np.amax(compania[:,-1]))
print(np.amin(compania[:,-1]))

* calculo del percentil de una columna

In [281]:
print(np.percentile(compania[:,-1], 90))

2184.0


* info varias

In [524]:
np.sctypes

{'int': [numpy.int8, numpy.int16, numpy.int32, numpy.int64],
 'uint': [numpy.uint8, numpy.uint16, numpy.uint32, numpy.uint64],
 'float': [numpy.float16, numpy.float32, numpy.float64],
 'complex': [numpy.complex64, numpy.complex128],
 'others': [bool, object, bytes, str, numpy.void]}

In [525]:
comp_array.__array_interface__

{'data': (2325855990400, False),
 'strides': (8, 800),
 'descr': [('', '|O')],
 'typestr': '|O',
 'shape': (100, 3),
 'version': 3}

In [526]:
comp_array[:2].__array_interface__['data'][0]

2325855990400

In [527]:
import cProfile
import re

cProfile.run('comp_array *= 2')

         3 function calls in 0.000 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}




* form de ordenar valores de una array

In [529]:
arr = np.array([1, 3, 2, 4, 5])
ordeno = arr.argsort()[-3:][::-1]
ordeno

array([4, 3, 1], dtype=int64)